# Generated by Django 4.2 on 2023-05-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
