# Generated by Django 4.2 on 2023-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('NEWS', 'Новость')], default='NEWS', max_length=7),
        ),
    ]
