# Generated by Django 4.2 on 2023-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0005_alter_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanAddPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_add_post', 'Can add post'),),
            },
        ),
    ]
