# Generated by Django 4.2 on 2023-05-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0006_canaddpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanAddPost',
        ),
    ]
