# Generated by Django 4.2 on 2023-05-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
