# Generated by Django 4.2 on 2023-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0014_subscribedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedusers',
            name='category',
            field=models.ManyToManyField(to='NewsPortal.category'),
        ),
    ]
