# Generated by Django 4.2 on 2023-05-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0016_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
    ]
