# Generated by Django 4.2 on 2023-05-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0017_rename_name_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
