# Generated by Django 4.2 on 2023-05-11 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortal', '0020_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='subscribed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
