# Generated by Django 4.2 on 2023-05-12 16:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0021_remove_subscribedusers_category_category_subscribe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name=django.contrib.auth.models.User)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
