# Generated by Django 4.2 on 2023-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0025_categorysubscribe_postcategory_delete_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
